AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sync-item-metadata-to-scsb-service'

Resources:
  SyncItemMetadataToScsbService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: SyncItemMetadataToScsbService-development
      Handler: app.handle_event
      Runtime: ruby3.3
      Timeout: 10
      Role: arn:aws:iam::224280085904:role/lambda_basic_execution
      Environment:
        Variables:
          SQS_QUEUE_URL: na
